"""add inn and legal_name column to addresses

Revision ID: 48bbf85472c3
Revises: ef687f00d9d2
Create Date: 2024-10-16 11:24:38.113317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bbf85472c3'
down_revision: Union[str, None] = 'ef687f00d9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('inn', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('legal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'legal_name')
    op.drop_column('addresses', 'inn')
    # ### end Alembic commands ###
