"""init

Revision ID: 89e2c91e1b21
Revises: 
Create Date: 2024-08-27 09:03:00.852840

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '89e2c91e1b21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_url',
                    sa.Column('point_id', sa.Integer(), nullable=False),
                    sa.Column('clean_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
                    sa.Column('city', sa.String(), nullable=True),
                    sa.Column('slug', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('point_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address_url')
    # ### end Alembic commands ###
