"""create Declare models

Revision ID: c65ccd4fec38
Revises: d220e94b7d9c
Create Date: 2024-08-28 09:45:22.110705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65ccd4fec38'
down_revision: Union[str, None] = 'd220e94b7d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_url', 'clean_url',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('address_url', 'city',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('address_url', 'slug',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_url', 'slug',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('address_url', 'city',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('address_url', 'clean_url',
                    existing_type=sa.TEXT(),
                    nullable=True)
    # ### end Alembic commands ###
