"""init_db

Revision ID: ee9db9c08a41
Revises: 
Create Date: 2024-08-29 16:33:44.078849

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ee9db9c08a41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_url',
                    sa.Column('point_id', sa.BigInteger(), nullable=False),
                    sa.Column('clean_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('slug', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('point_id')
                    )
    op.create_table('addresses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('code', sa.String(), nullable=True),
                    sa.Column('chicago_code', sa.BigInteger(), nullable=True),
                    sa.Column('point_id', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('ya_name', sa.String(), nullable=True),
                    sa.Column('category', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('full_address', sa.String(), nullable=False),
                    sa.Column('phone', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('department', sa.String(), nullable=True),
                    sa.Column('request_address', sa.String(), nullable=False),
                    sa.Column('country_code', sa.String(length=10), nullable=True),
                    sa.Column('formatted', sa.String(), nullable=False),
                    sa.Column('zip_code', sa.String(), nullable=True),
                    sa.Column('country', sa.String(), nullable=True),
                    sa.Column('province', sa.String(), nullable=True),
                    sa.Column('area', sa.String(), nullable=True),
                    sa.Column('city', sa.String(), nullable=True),
                    sa.Column('street', sa.String(), nullable=True),
                    sa.Column('house_number', sa.String(), nullable=True),
                    sa.Column('latitude', sa.String(), nullable=True),
                    sa.Column('longitude', sa.String(), nullable=True),
                    sa.Column('source_url', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('response_count',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_count')
    op.drop_table('addresses')
    op.drop_table('address_url')
    # ### end Alembic commands ###
